/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain;


import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ru.xpendence.jooqexample.domain.tables.Cities;
import ru.xpendence.jooqexample.domain.tables.Countries;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CITIES_PKEY = Indexes0.CITIES_PKEY;
    public static final Index COUNTRIES_PKEY = Indexes0.COUNTRIES_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CITIES_PKEY = Internal.createIndex("cities_pkey", Cities.CITIES, new OrderField[] { Cities.CITIES.ID }, true);
        public static Index COUNTRIES_PKEY = Internal.createIndex("countries_pkey", Countries.COUNTRIES, new OrderField[] { Countries.COUNTRIES.ID }, true);
    }
}
