/*
 * This file is generated by jOOQ.
 */
package ru.xpendence.jooqexample.domain;


import javax.annotation.processing.Generated;

import ru.xpendence.jooqexample.domain.tables.Cities;
import ru.xpendence.jooqexample.domain.tables.Countries;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.cities</code>.
     */
    public static final Cities CITIES = Cities.CITIES;

    /**
     * The table <code>public.countries</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;
}
